<?xml version="1.0" encoding="UTF-8"?>
<!--
/*
 * Copyright 2004 The Apache Software Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 -->
<!DOCTYPE nodeTypes [
	<!ELEMENT nodeTypes (nodeType)*>
		<!ELEMENT nodeType (propertyDef|childNodeDef)*>
		<!ATTLIST nodeType
			name CDATA #REQUIRED
			mixin (true|false) #REQUIRED
 			orderableChildNodes (true|false) #REQUIRED
			supertypes CDATA #REQUIRED
		>
		<!ELEMENT propertyDef (#PCDATA)>
		<!ATTLIST propertyDef
			name CDATA #REQUIRED
			type (String|Date|Path|Name|Reference|Binary|Double|Long|Boolean|undefined) #REQUIRED
			valueConstraint CDATA #REQUIRED
			defaultValues CDATA #REQUIRED
			autoCreate (true|false) #REQUIRED
			mandatory (true|false) #REQUIRED
			onParentVersion (COPY|VERSION|INITIALIZE|COMPUTE|IGNORE|ABORT) #REQUIRED
			protected (true|false) #REQUIRED
			primaryItem (true|false) #REQUIRED
			multiple  (true|false) #REQUIRED
		>
		<!ELEMENT childNodeDef (#PCDATA)>
		<!ATTLIST childNodeDef
			name CDATA #REQUIRED
			requiredPrimaryTypes CDATA #REQUIRED
			defaultPrimaryType  CDATA #REQUIRED
			autoCreate (true|false) #REQUIRED
			mandatory (true|false) #REQUIRED
			onParentVersion (COPY|VERSION|INITIALIZE|COMPUTE|IGNORE|ABORT) #REQUIRED
			protected (true|false) #REQUIRED
			primaryItem (true|false) #REQUIRED
			sameNameSibs (true|false) #REQUIRED
		>
]>
<nodeTypes
    xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
    xmlns:mix="http://www.jcp.org/jcr/mix/1.0"
    xmlns:jcr="http://www.jcp.org/jcr/1.0">

    <!-- primary types !-->
    <nodeType name="nt:base" mixin="false" orderableChildNodes="false" supertypes="">
	<propertyDef name="jcr:primaryType" type="Name" valueConstraint="" defaultValues="" autoCreate="true" mandatory="true" onParentVersion="COMPUTE" protected="true" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:mixinTypes" type="Name" valueConstraint="" defaultValues="" autoCreate="false" mandatory="false" onParentVersion="COMPUTE" protected="true" primaryItem="false" multiple="true"/>
    </nodeType>
    <nodeType name="nt:unstructured" mixin="false" orderableChildNodes="true" supertypes="nt:base">
	<childNodeDef name="" requiredPrimaryTypes="nt:base" defaultPrimaryType="nt:unstructured" autoCreate="false" mandatory="false" onParentVersion="COPY" protected="false" primaryItem="false" sameNameSibs="true"/>
	<propertyDef name="" type="undefined" valueConstraint="" defaultValues="" autoCreate="false" mandatory="false" onParentVersion="COPY" protected="false" primaryItem="false" multiple="true"/>
	<propertyDef name="" type="undefined" valueConstraint="" defaultValues="" autoCreate="false" mandatory="false" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
    </nodeType>
    <nodeType name="nt:hierarchyNode" mixin="false" orderableChildNodes="false" supertypes="nt:base">
	<propertyDef name="jcr:created" type="Date" valueConstraint="" defaultValues="" autoCreate="true" mandatory="true" onParentVersion="INITIALIZE" protected="true" primaryItem="false" multiple="false"/>
    </nodeType>
    <nodeType name="nt:file" mixin="false" orderableChildNodes="false" supertypes="nt:hierarchyNode">
	<childNodeDef name="jcr:content" requiredPrimaryTypes="nt:base" defaultPrimaryType="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="true" sameNameSibs="false"/>
    </nodeType>
    <nodeType name="nt:mimeResource" mixin="false" orderableChildNodes="false" supertypes="nt:base,mix:referenceable">
	<propertyDef name="jcr:encoding" type="String" valueConstraint="" defaultValues="" autoCreate="false" mandatory="false" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:mimeType" type="String" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:data" type="Binary" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="true" multiple="false"/>
	<propertyDef name="jcr:lastModified" type="Date" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COMPUTE" protected="false" primaryItem="false" multiple="false"/>
    </nodeType>
    <nodeType name="nt:folder" mixin="false" orderableChildNodes="false" supertypes="nt:hierarchyNode">
	<childNodeDef name="" requiredPrimaryTypes="nt:hierarchyNode" defaultPrimaryType="" autoCreate="false" mandatory="false" onParentVersion="VERSION" protected="false" primaryItem="false" sameNameSibs="false"/>
    </nodeType>
    <nodeType name="nt:nodeType" mixin="false" orderableChildNodes="false" supertypes="nt:base">
	<propertyDef name="jcr:nodeTypeName" type="Name" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:supertypes" type="Name" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="true"/>
	<propertyDef name="jcr:isMixin" type="Boolean" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:orderableChildNodes" type="Boolean" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<childNodeDef name="jcr:propertyDef" requiredPrimaryTypes="nt:propertyDef" defaultPrimaryType="nt:propertyDef" autoCreate="false" mandatory="false" onParentVersion="VERSION" protected="false" primaryItem="false" sameNameSibs="true"/>
	<childNodeDef name="jcr:childNodeDef" requiredPrimaryTypes="nt:childNodeDef" defaultPrimaryType="nt:childNodeDef" autoCreate="false" mandatory="false" onParentVersion="VERSION" protected="false" primaryItem="false" sameNameSibs="true"/>
    </nodeType>
    <nodeType name="nt:propertyDef" mixin="false" orderableChildNodes="false" supertypes="nt:base">
	<propertyDef name="jcr:name" type="Name" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:type" type="String" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:valueConstraint" type="String" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:defaultValues" type="undefined" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:autoCreate" type="Boolean" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:mandatory" type="Boolean" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:onParentVersion" type="String" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:protected" type="Boolean" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:primaryItem" type="Boolean" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:multiple" type="Boolean" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
    </nodeType>
    <nodeType name="nt:childNodeDef" mixin="false" orderableChildNodes="false" supertypes="nt:base">
	<propertyDef name="jcr:name" type="Name" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:requiredPrimaryTypes" type="String" valueConstraint="" defaultValues="nt:base" autoCreate="true" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="true"/>
	<propertyDef name="jcr:defaultPrimaryType" type="String" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:autoCreate" type="Boolean" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:mandatory" type="Boolean" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:onParentVersion" type="String" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:protected" type="Boolean" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:primaryItem" type="Boolean" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:sameNameSibs" type="Boolean" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
    </nodeType>
    <nodeType name="nt:versionHistory" mixin="false" orderableChildNodes="false" supertypes="nt:base,mix:referenceable">
	<childNodeDef name="jcr:rootVersion" requiredPrimaryTypes="nt:version" defaultPrimaryType="nt:version" autoCreate="true" mandatory="true" onParentVersion="ABORT" protected="true" primaryItem="false" sameNameSibs="false"/>
	<childNodeDef name="" requiredPrimaryTypes="nt:version" defaultPrimaryType="nt:version" autoCreate="false" mandatory="false" onParentVersion="ABORT" protected="true" primaryItem="false" sameNameSibs="false"/>
    </nodeType>
    <nodeType name="nt:frozenVersionableChild" mixin="false" orderableChildNodes="false" supertypes="nt:base">
	<propertyDef name="jcr:versionHistory" type="Reference" valueConstraint="nt:versionHistory" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="ABORT" protected="true" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:baseVersion" type="Reference" valueConstraint="nt:version" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="ABORT" protected="true" primaryItem="false" multiple="false"/>
    </nodeType>
    <nodeType name="nt:frozen" mixin="false" orderableChildNodes="false" supertypes="nt:base">
	<propertyDef name="jcr:frozenPrimaryType" type="Name" valueConstraint="" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="ABORT" protected="true" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:frozenMixinTypes" type="Name" valueConstraint="" defaultValues="" autoCreate="false" mandatory="false" onParentVersion="ABORT" protected="true" primaryItem="false" multiple="true"/>
	<propertyDef name="jcr:frozenUUID" type="String" valueConstraint="" defaultValues="" autoCreate="false" mandatory="false" onParentVersion="ABORT" protected="true" primaryItem="false" multiple="false"/>
	<propertyDef name="" type="undefined" valueConstraint="" defaultValues="" autoCreate="false" mandatory="false" onParentVersion="ABORT" protected="true" primaryItem="false" multiple="true"/>
	<propertyDef name="" type="undefined" valueConstraint="" defaultValues="" autoCreate="false" mandatory="false" onParentVersion="ABORT" protected="true" primaryItem="false" multiple="false"/>
	<childNodeDef name="" requiredPrimaryTypes="nt:base" defaultPrimaryType="nt:frozen" autoCreate="false" mandatory="false" onParentVersion="ABORT" protected="true" primaryItem="false" sameNameSibs="true"/>
    </nodeType>
    <nodeType name="nt:version" mixin="false" orderableChildNodes="false" supertypes="nt:frozen,mix:referenceable">
	<propertyDef name="jcr:versionLabels" type="String" valueConstraint="" defaultValues="" autoCreate="false" mandatory="false" onParentVersion="ABORT" protected="true" primaryItem="false" multiple="true"/>
	<propertyDef name="jcr:created" type="Date" valueConstraint="" defaultValues="" autoCreate="true" mandatory="true" onParentVersion="ABORT" protected="true" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:predecessors" type="Reference" valueConstraint="nt:version" defaultValues="" autoCreate="true" mandatory="true" onParentVersion="ABORT" protected="true" primaryItem="false" multiple="true"/>
	<propertyDef name="jcr:successors" type="Reference" valueConstraint="nt:version" defaultValues="" autoCreate="true" mandatory="true" onParentVersion="ABORT" protected="true" primaryItem="false" multiple="true"/>
    </nodeType>
    <nodeType name="nt:query" mixin="false" orderableChildNodes="false" supertypes="nt:base">
	<propertyDef name="jcr:statement" type="String" valueConstraint="" defaultValues="" autoCreate="false" mandatory="false" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:language" type="String" valueConstraint="" defaultValues="" autoCreate="false" mandatory="false" onParentVersion="COPY" protected="false" primaryItem="false" multiple="false"/>
    </nodeType>

    <!-- mixin types !-->
    <nodeType name="mix:accessControllable" mixin="true" orderableChildNodes="false" supertypes="">
    </nodeType>
    <nodeType name="mix:lockable" mixin="true" orderableChildNodes="false" supertypes="">
	<propertyDef name="jcr:lockOwner" type="String" valueConstraint="" defaultValues="" autoCreate="false" mandatory="false" onParentVersion="IGNORE" protected="true" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:lockIsDeep" type="Boolean" valueConstraint="" defaultValues="" autoCreate="false" mandatory="false" onParentVersion="IGNORE" protected="true" primaryItem="false" multiple="false"/>
    </nodeType>
    <nodeType name="mix:referenceable" mixin="true" orderableChildNodes="false" supertypes="">
	<propertyDef name="jcr:uuid" type="String" valueConstraint="" defaultValues="" autoCreate="true" mandatory="true" onParentVersion="INITIALIZE" protected="true" primaryItem="false" multiple="false"/>
    </nodeType>
    <nodeType name="mix:versionable" mixin="true" orderableChildNodes="false" supertypes="mix:referenceable">
	<propertyDef name="jcr:versionHistory" type="Reference" valueConstraint="nt:versionHistory" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="true" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:baseVersion" type="Reference" valueConstraint="nt:version" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="IGNORE" protected="true" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:isCheckedOut" type="Boolean" valueConstraint="" defaultValues="true" autoCreate="false" mandatory="true" onParentVersion="IGNORE" protected="true" primaryItem="false" multiple="false"/>
	<propertyDef name="jcr:predecessors" type="Reference" valueConstraint="nt:version" defaultValues="" autoCreate="false" mandatory="true" onParentVersion="COPY" protected="true" primaryItem="false" multiple="true"/>
    </nodeType>
</nodeTypes>