<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Repositories [
  <!ELEMENT Repositories (Repository+)>
  <!ELEMENT Repository (RepositoryStore,StableWorkspace+)>
  <!ATTLIST Repository
    name CDATA #REQUIRED>
  <!ELEMENT RepositoryStore (FileSystem)>
  <!ELEMENT StableWorkspace (PersistenceManager,WorkspaceStore,BLOBStore?,DynamicWorkspace*)>
  <!ATTLIST StableWorkspace
    name CDATA #REQUIRED>
  <!ELEMENT PersistenceManager (param*)>
  <!ATTLIST PersistenceManager
    class CDATA #REQUIRED>
  <!ELEMENT WorkspaceStore (FileSystem)>
  <!ELEMENT BLOBStore (FileSystem)>
  <!ELEMENT DynamicWorkspace (PersistenceManager,WorkspaceStore,BLOBStore?)>
  <!ATTLIST DynamicWorkspace
    name CDATA #REQUIRED>
  <!ELEMENT FileSystem (param*)>
  <!ATTLIST FileSystem
    class CDATA #REQUIRED>
  <!ELEMENT param EMPTY>
  <!ATTLIST param
    name CDATA #REQUIRED
    value CDATA #REQUIRED>]>

<Repositories>
    <!-- sample configuration for a repository that stores its state in a local file system -->
    <Repository name="localfs">
	<RepositoryStore>
	    <FileSystem class="org.apache.jackrabbit.core.fs.local.LocalFileSystem">
		<param name="path" value="${factory.home}/repositories/localfs/repository"/>
	    </FileSystem>
	</RepositoryStore>
	<!-- main workspace -->
	<StableWorkspace name="default">
	    <PersistenceManager class="org.apache.jackrabbit.core.state.xml.XMLPersistenceManager"/>
	    <WorkspaceStore>
		<FileSystem class="org.apache.jackrabbit.core.fs.local.LocalFileSystem">
		    <param name="path" value="${factory.home}/repositories/localfs/workspaces/default/data"/>
		</FileSystem>
	    </WorkspaceStore>
	    <BLOBStore>
		<FileSystem class="org.apache.jackrabbit.core.fs.local.LocalFileSystem">
		    <param name="path" value="${factory.home}/repositories/localfs/workspaces/default/blobs"/>
		</FileSystem>
	    </BLOBStore>
	</StableWorkspace>
    </Repository>
</Repositories>